import fs from "fs";
import path from "path";

const CONTRACTS_DIR = path.resolve(__dirname, "..");
const ARTIFACTS_DIR = path.resolve(CONTRACTS_DIR, "artifacts");
const OUTPUT_PATH = path.resolve(CONTRACTS_DIR, "../../apps/zugov-frontend/src/generated/abis.ts");

/**
 * Contracts the browser frontend interacts with via `X__factory.connect(...)`.
 * Only MACI is ever deployed from raw bytecode in the browser (new communities'
 * MACI instance) — everything else just needs its ABI to call an already-deployed
 * contract, so bytecode is intentionally omitted for the rest to keep this lean.
 */
const CONTRACTS: { exportName: string; artifactPath: string; includeBytecode?: boolean }[] = [
  { exportName: "MACI", artifactPath: "contracts/MACI.sol/MACI.json", includeBytecode: true },
  { exportName: "POLL", artifactPath: "contracts/Poll.sol/Poll.json" },
  {
    exportName: "BASE_POLICY",
    artifactPath: "@excubiae/contracts/contracts/policy/BasePolicy.sol/BasePolicy.json",
  },
  {
    exportName: "BASE_CHECKER",
    artifactPath: "@excubiae/contracts/contracts/checker/BaseChecker.sol/BaseChecker.json",
  },
  {
    exportName: "FREE_FOR_ALL_POLICY",
    artifactPath: "@excubiae/contracts/contracts/extensions/freeForAll/FreeForAllPolicy.sol/FreeForAllPolicy.json",
  },
  {
    exportName: "FREE_FOR_ALL_POLICY_FACTORY",
    artifactPath:
      "@excubiae/contracts/contracts/extensions/freeForAll/FreeForAllPolicyFactory.sol/FreeForAllPolicyFactory.json",
  },
  {
    exportName: "CONSTANT_VOICE_CREDIT_PROXY_FACTORY",
    artifactPath:
      "contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxyFactory.sol/ConstantInitialVoiceCreditProxyFactory.json",
  },
];

interface IArtifact {
  abi: unknown[];
  bytecode: string;
}

function main(): void {
  const sections = CONTRACTS.map(({ exportName, artifactPath, includeBytecode }) => {
    const fullPath = path.resolve(ARTIFACTS_DIR, artifactPath);

    if (!fs.existsSync(fullPath)) {
      throw new Error(`Artifact not found: ${fullPath} (run \`pnpm run compileSol\` first)`);
    }

    const artifact = JSON.parse(fs.readFileSync(fullPath, "utf8")) as IArtifact;
    const abiLine = `export const ${exportName}_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
    const bytecodeLine = includeBytecode ? `\n\nexport const ${exportName}_BYTECODE = "${artifact.bytecode}";` : "";

    return `// Source: packages/contracts/artifacts/${artifactPath}\n${abiLine}${bytecodeLine}`;
  });

  const output = `/**
 * AUTO-GENERATED by packages/contracts/scripts/syncFrontendAbis.ts — do not edit by hand.
 * Regenerate with: pnpm run sync-frontend-abis (also runs automatically after compileSol).
 *
 * Copied verbatim from the compiled artifacts so these can never drift from what's actually
 * deployed. Only contracts the browser frontend calls via X__factory.connect(...) are included.
 */

${sections.join("\n\n")}
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output);

  // eslint-disable-next-line no-console
  console.log(`Wrote frontend ABIs to ${OUTPUT_PATH}`);
}

main();
