ALTER TABLE "categories" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "communities" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "communities" ALTER COLUMN "registered_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "community_decision_adapters" ALTER COLUMN "attached_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "community_discussions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "credentials" ALTER COLUMN "last_checked_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "credentials" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "eligibility_rules" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "eligibility_rulesets" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "eligibility_rulesets" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "event_rsvps" ALTER COLUMN "rsvped_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "event_rsvps" ALTER COLUMN "cancelled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "start_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "end_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "cancelled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "join_requests" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "join_requests" ALTER COLUMN "resolved_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "membership_tiers" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "memberships" ALTER COLUMN "joined_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposal_sponsors" ALTER COLUMN "sponsored_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "poll_start_date" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "poll_end_date" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "formalized_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "tally_requested_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "tally_completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "withdrawn_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "nonce_expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "union_memberships" ALTER COLUMN "requested_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "union_memberships" ALTER COLUMN "responded_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "union_memberships" ALTER COLUMN "left_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "venues" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "zupoll_identity_commitments" ALTER COLUMN "registered_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "zupoll_proposal_groups" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "zupoll_votes" ALTER COLUMN "cast_at" SET DATA TYPE bigint;